# Generated by Django 3.1.7 on 2021-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='IP_address',
            field=models.CharField(default='', max_length=16),
        ),
    ]
