# Generated by Django 3.1.7 on 2021-04-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210408_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='ip',
        ),
        migrations.AddField(
            model_name='hostname',
            name='ip_address',
            field=models.ForeignKey(max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_data'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='IP_address',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
