# Generated by Django 3.1.7 on 2021-04-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210408_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='IP',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='ip_address',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_data'),
        ),
    ]
